/*
 * The MIT License
 *
 * Copyright 2016 mprabhu.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.manoharprabhu;

import com.manoharprabhu.services.DataStore;
import com.manoharprabhu.services.DatabaseService;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author mprabhu
 */
public class TableConfigurationFrame extends javax.swing.JFrame {

    /**
     * Creates new form TableConfigurationFrame
     */
    private String selectedTable = "";
    Long val = 1L;
    Long min = Long.MIN_VALUE;
    Long max = Long.MAX_VALUE;
    Long step = 1L;

    public TableConfigurationFrame() {
        initComponents();
        populateConfigureColumn();
    }

    private void populateConfigureColumn() {
        final TableConfigurationFrame self = this;
        (new Thread(() -> {
            DatabaseService databaseService = DataStore.getDatabaseServiceInstance();
            final List<Map<String, String>> tableList = databaseService.getColumnNamesAndAttributes(self.selectedTable);
            DataStore.setColumnNameTypeList(tableList);
            final List<String> comboData = new ArrayList<>();
            tableList.stream().forEach((item) -> {
                comboData.add(item.get("column_name"));
            });
            SwingUtilities.invokeLater(() -> {
                configuredColumnsCombo.setModel(new DefaultComboBoxModel(comboData.toArray()));
            });
        })).start();
    }

    public void setTableSelected(String table) {
        this.selectedTable = table;
        this.tableSelected.setText(table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableSelected = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        configuredColumnsCombo = new javax.swing.JComboBox();
        configureButton = new javax.swing.JButton();
        generateDataButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numberOfRowsToGenerateSpinner = new javax.swing.JSpinner(new SpinnerNumberModel(val, min, max, step));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableSelected.setEditable(false);
        tableSelected.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Configure column:");

        configureButton.setText("Configure");
        configureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configureButtonActionPerformed(evt);
            }
        });

        generateDataButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        generateDataButton.setText("Generate data");
        generateDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateDataButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Number of rows to generate:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(configuredColumnsCombo, 0, 342, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(configureButton))
                    .addComponent(tableSelected)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberOfRowsToGenerateSpinner))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generateDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(configuredColumnsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(configureButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numberOfRowsToGenerateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(generateDataButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configureButtonActionPerformed
        if (configuredColumnsCombo.getSelectedIndex() == -1) {
            return;
        }
        String selectedColumn = (String) configuredColumnsCombo.getSelectedItem();
        String columnType = DataStore.getTypeOfColumn(selectedColumn);
        DatabaseService databaseService = DataStore.getDatabaseServiceInstance();
        if ("number".equals(databaseService.getTypeOfColumn(columnType))) {
            NumberConfigurationForm numberConfigurationForm = new NumberConfigurationForm(selectedColumn);
            numberConfigurationForm.setVisible(true);
        }
    }//GEN-LAST:event_configureButtonActionPerformed

    private void generateDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateDataButtonActionPerformed
        Long numberOfRowsToGenerate = (Long)numberOfRowsToGenerateSpinner.getValue();
        if(numberOfRowsToGenerate <= 0) {
            JOptionPane.showMessageDialog(this, "Number of rows to generate must be greater than 0.");
            return;
        }
        GenerateDataProgress generateDataProgress = new GenerateDataProgress(numberOfRowsToGenerate);
        generateDataProgress.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_generateDataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableConfigurationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configureButton;
    private javax.swing.JComboBox configuredColumnsCombo;
    private javax.swing.JButton generateDataButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner numberOfRowsToGenerateSpinner;
    private javax.swing.JTextField tableSelected;
    // End of variables declaration//GEN-END:variables
}
